{% set name = "trampolim" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/trampolim-{{ version }}.tar.gz
  sha256: f4ca5a4cf6ba7adb252cf1972799da6a63d4d587dc59813a555df2080760c264

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - trampolim = trampolim.__main__:entrypoint

requirements:
  host:
    - packaging
    - pep621 >=0.4.0
    - pip
    - python {{ python_min }}
    - tomli >=1.0.0
    - setuptools
  run:
    - backports.cached-property
    - packaging
    - pep621 >=0.4.0
    - python >={{ python_min }}
    - tomli >=1.0.0

test:
  imports:
    - trampolim
  commands:
    - pip check
    - trampolim --help
  requires:
    - pip
    - rich
    - python {{ python_min }}

about:
  home: https://github.com/FFY00/trampolim
  doc_url: https://trampolim.readthedocs.io/
  summary: A modern Python build backend
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
